### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by broyuken** [andrei-ace/music-cloud#22]
I'm following a combination of your github and medium links and have come across an issue uploading my files. The file was uploaded to dropbox, but something else is not happy. Is it an issue with my mp3 metadata or is it something else?

```
administrator@ubuntu-desktop-vm:~/music-cloud/dropbox-catalog$ node index upload -d ./mp3/
Uploaded: mp3/white_noise.mp3
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Hash.update (node:internal/crypto/hash:107:11)
    at hash (/home/administrator/music-cloud/dropbox-catalog/index.js:69:38)
    at shareFromDropbox (/home/administrator/music-cloud/dropbox-catalog/index.js:64:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
administrator@ubuntu-desktop-vm:~/music-cloud/dropbox-catalog$
```

**Comment by broyuken** [comment]
If it helps, I'm on node v20.6.0 and npm 9.8.1

**Comment by broyuken** [comment]
nevermind, the artist tag wasn't there, I added it and it uploaded fine.
